
import java.awt.Color;
import java.util.Random;
//import java.util.Timer;
//import java.util.TimerTask;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author EPF
 */
public class fenetreDeJeu extends javax.swing.JFrame {
        int cpt_pts;
        int record = 0;
        int  nb_parties = -1;
        int cpt_coup = 0;
        Timer chrono;
        
    /**
     * Creates new form fenetreDeJeu
     */
    public fenetreDeJeu() {
        initComponents();
        InitialiserPartie();
        
        ActionListener tache_recur= new ActionListener() {
            int time = 30;
            
            @Override
            public void actionPerformed(ActionEvent e1) {
                
                if (time == 0) {
                    System.out.println("Temps écoulé ! ");
                    chrono.stop();
                }
                
                time--;
                tps_rest.setText(time + "");
                System.out.println(time);
                
                
            }
        ;};
        
        
        
         Timer chrono = new Timer(1000, tache_recur);       
         
        chrono.start();
        
       /* chrono.schedule(new TimerTask(){
            
            int time = 30;
            
            @Override
            public void run(){
                
                if (time == 0) {
                    System.out.println("Temps écoulé ! ");
                    cancel();
                    
                }
                
                time --;
                System.out.println(time);
                tps_rest.setText(time +"");
                
            }
        }, 30000 , 1000); */ //attention temps en ms : pour 1sec delay = 1000
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked") 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panneau_grille = new javax.swing.JPanel();
        Bouton1 = new javax.swing.JButton();
        Bouton2 = new javax.swing.JButton();
        Bouton3 = new javax.swing.JButton();
        Bouton4 = new javax.swing.JButton();
        Bouton5 = new javax.swing.JButton();
        Bouton6 = new javax.swing.JButton();
        Bouton7 = new javax.swing.JButton();
        Bouton8 = new javax.swing.JButton();
        Bouton9 = new javax.swing.JButton();
        panneau_nom = new javax.swing.JPanel();
        panneau_chrono = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tps_rest = new javax.swing.JLabel();
        panneau_scores = new javax.swing.JPanel();
        jlab1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Label_Record = new javax.swing.JLabel();
        Label_Score = new javax.swing.JLabel();
        score_max = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nb_part = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panneau_grille.setBackground(new java.awt.Color(153, 153, 153));
        panneau_grille.setLayout(new java.awt.GridLayout(3, 3));

        Bouton1.setBackground(new java.awt.Color(0, 0, 204));
        Bouton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton1ActionPerformed(evt);
            }
        });
        panneau_grille.add(Bouton1);

        Bouton2.setBackground(new java.awt.Color(0, 0, 204));
        Bouton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton2ActionPerformed(evt);
            }
        });
        panneau_grille.add(Bouton2);

        Bouton3.setBackground(new java.awt.Color(0, 0, 204));
        Bouton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton3ActionPerformed(evt);
            }
        });
        panneau_grille.add(Bouton3);

        Bouton4.setBackground(new java.awt.Color(0, 0, 204));
        Bouton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton4ActionPerformed(evt);
            }
        });
        panneau_grille.add(Bouton4);

        Bouton5.setBackground(new java.awt.Color(0, 0, 204));
        Bouton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton5ActionPerformed(evt);
            }
        });
        panneau_grille.add(Bouton5);

        Bouton6.setBackground(new java.awt.Color(0, 0, 204));
        Bouton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton6ActionPerformed(evt);
            }
        });
        panneau_grille.add(Bouton6);

        Bouton7.setBackground(new java.awt.Color(0, 0, 204));
        Bouton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton7ActionPerformed(evt);
            }
        });
        panneau_grille.add(Bouton7);

        Bouton8.setBackground(new java.awt.Color(0, 0, 204));
        Bouton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton8ActionPerformed(evt);
            }
        });
        panneau_grille.add(Bouton8);

        Bouton9.setBackground(new java.awt.Color(0, 0, 204));
        Bouton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton9ActionPerformed(evt);
            }
        });
        panneau_grille.add(Bouton9);

        getContentPane().add(panneau_grille, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 410, 440));

        panneau_nom.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout panneau_nomLayout = new javax.swing.GroupLayout(panneau_nom);
        panneau_nom.setLayout(panneau_nomLayout);
        panneau_nomLayout.setHorizontalGroup(
            panneau_nomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        panneau_nomLayout.setVerticalGroup(
            panneau_nomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(panneau_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 430, -1));

        panneau_chrono.setBackground(new java.awt.Color(0, 255, 255));

        jLabel3.setText("Chrono");

        jLabel4.setText("sec");

        javax.swing.GroupLayout panneau_chronoLayout = new javax.swing.GroupLayout(panneau_chrono);
        panneau_chrono.setLayout(panneau_chronoLayout);
        panneau_chronoLayout.setHorizontalGroup(
            panneau_chronoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panneau_chronoLayout.createSequentialGroup()
                .addGroup(panneau_chronoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panneau_chronoLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE))
                    .addGroup(panneau_chronoLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(tps_rest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addComponent(jLabel4)
                .addGap(37, 37, 37))
        );
        panneau_chronoLayout.setVerticalGroup(
            panneau_chronoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panneau_chronoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panneau_chronoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tps_rest, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panneau_chronoLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        getContentPane().add(panneau_chrono, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 280, -1));

        panneau_scores.setBackground(new java.awt.Color(204, 204, 204));

        jlab1.setText("Scores");

        jLabel1.setText("Score actuel :");

        Label_Record.setText("Record :");

        jButton10.setText("Rejouer");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre de parties jouées :");

        javax.swing.GroupLayout panneau_scoresLayout = new javax.swing.GroupLayout(panneau_scores);
        panneau_scores.setLayout(panneau_scoresLayout);
        panneau_scoresLayout.setHorizontalGroup(
            panneau_scoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panneau_scoresLayout.createSequentialGroup()
                .addGroup(panneau_scoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panneau_scoresLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jlab1))
                    .addGroup(panneau_scoresLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(panneau_scoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(Label_Record)
                            .addComponent(jLabel2))
                        .addGroup(panneau_scoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panneau_scoresLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(panneau_scoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(score_max, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nb_part, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panneau_scoresLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Label_Score, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panneau_scoresLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jButton10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panneau_scoresLayout.setVerticalGroup(
            panneau_scoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panneau_scoresLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jlab1)
                .addGap(36, 36, 36)
                .addGroup(panneau_scoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Score, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(41, 41, 41)
                .addGroup(panneau_scoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(score_max, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Record))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(panneau_scoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nb_part, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(23, 23, 23)
                .addComponent(jButton10)
                .addGap(38, 38, 38))
        );

        getContentPane().add(panneau_scores, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, 260, 290));

        setBounds(0, 0, 814, 613);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        //chrono.stop();
        InitialiserPartie();
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void Bouton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton1ActionPerformed
        // TODO add your handling code here:
        
        if (Bouton1.getBackground() == Color.CYAN) {
            Bouton1.setBackground(Color.BLUE);
            supp_bouton_blanc();
            allumerCaseAlea();
            cpt_pts += 1;
            Label_Score.setText(cpt_pts + "");
            cpt_coup += 1;
            if (cpt_coup == 1) {
              chrono.start();
              
            }
        }
        else if(Bouton1.getBackground() == Color.white) {
            cpt_pts -= 3;
            Label_Score.setText(cpt_pts + "");
            Bouton1.setBackground(Color.BLUE);
            
        }
        else{
            cpt_pts -= 1;
            Label_Score.setText(cpt_pts + "");
        }
    }//GEN-LAST:event_Bouton1ActionPerformed

    private void Bouton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton5ActionPerformed
        // TODO add your handling code here:
        
        if (Bouton5.getBackground() == Color.CYAN) {
            Bouton5.setBackground(Color.BLUE);
            supp_bouton_blanc();
            allumerCaseAlea();
            cpt_pts += 1;
            Label_Score.setText(cpt_pts + "");
            cpt_coup += 1;
            if (cpt_coup == 1) {
              chrono.start();
              
            }
        }
        else if(Bouton5.getBackground() == Color.white) {
            cpt_pts -= 3;
            Label_Score.setText(cpt_pts + "");
            Bouton5.setBackground(Color.BLUE);
            
        }
        else{
            cpt_pts -= 1;
            Label_Score.setText(cpt_pts + "");
        }
    }//GEN-LAST:event_Bouton5ActionPerformed

    private void Bouton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton2ActionPerformed
        // TODO add your handling code here:
        
        if (Bouton2.getBackground() == Color.CYAN) {
            Bouton2.setBackground(Color.BLUE);
            supp_bouton_blanc();
            allumerCaseAlea();
            cpt_pts += 1;
            Label_Score.setText(cpt_pts + "");
            cpt_coup += 1;
            if (cpt_coup == 1) {
              chrono.start();
              
            }
        }
        else if(Bouton2.getBackground() == Color.white) {
            cpt_pts -= 3;
            Label_Score.setText(cpt_pts + "");
            Bouton2.setBackground(Color.BLUE);
            
        }
        else{
            cpt_pts -= 1;
            Label_Score.setText(cpt_pts + "");
        }
    }//GEN-LAST:event_Bouton2ActionPerformed

    private void Bouton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton3ActionPerformed
        // TODO add your handling code here:
        
        if (Bouton3.getBackground() == Color.CYAN) {
            Bouton3.setBackground(Color.BLUE);
            supp_bouton_blanc();
            allumerCaseAlea();
            cpt_pts += 1;
            Label_Score.setText(cpt_pts + "");
            cpt_coup += 1;
            if (cpt_coup == 1) {
              chrono.start();
              
            }
        }
        else if(Bouton3.getBackground() == Color.white) {
            cpt_pts -= 3;
            Label_Score.setText(cpt_pts + "");
            Bouton3.setBackground(Color.BLUE);
            
        }
        else{
            cpt_pts -= 1;
            Label_Score.setText(cpt_pts + "");
        }
    }//GEN-LAST:event_Bouton3ActionPerformed

    private void Bouton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton4ActionPerformed
        // TODO add your handling code here:
        
        if (Bouton4.getBackground() == Color.CYAN) {
            Bouton4.setBackground(Color.BLUE);
            supp_bouton_blanc();
            allumerCaseAlea();
            cpt_pts += 1;
            Label_Score.setText(cpt_pts + "");
            cpt_coup += 1;
            if (cpt_coup == 1) {
              chrono.start();
              
            }
        }
        else if(Bouton4.getBackground() == Color.white) {
            cpt_pts -= 3;
            Label_Score.setText(cpt_pts + "");
            Bouton4.setBackground(Color.BLUE);
            
        }
        else{
            cpt_pts -= 1;
            Label_Score.setText(cpt_pts + "");
        }
    }//GEN-LAST:event_Bouton4ActionPerformed

    private void Bouton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton6ActionPerformed
        // TODO add your handling code here:
        
        if (Bouton6.getBackground() == Color.CYAN) {
            Bouton6.setBackground(Color.BLUE);
            supp_bouton_blanc();
            allumerCaseAlea();
            cpt_pts += 1;
            Label_Score.setText(cpt_pts + "");
            cpt_coup += 1;
            if (cpt_coup == 1) {
              chrono.start();
              
            }
        }
        else if(Bouton6.getBackground() == Color.white) {
            cpt_pts -= 3;
            Label_Score.setText(cpt_pts + "");
            Bouton6.setBackground(Color.BLUE);
            
        }
        else{
            cpt_pts -= 1;
            Label_Score.setText(cpt_pts + "");
        }
    }//GEN-LAST:event_Bouton6ActionPerformed

    private void Bouton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton7ActionPerformed
        // TODO add your handling code here:
        
        if (Bouton7.getBackground() == Color.CYAN) {
            Bouton7.setBackground(Color.BLUE);
            supp_bouton_blanc();
            allumerCaseAlea();
            cpt_pts += 1;
            Label_Score.setText(cpt_pts + "");
            cpt_coup += 1;
            if (cpt_coup == 1) {
              chrono.start();
              
            }
        }
        else if(Bouton7.getBackground() == Color.white) {
            cpt_pts -= 3;
            Label_Score.setText(cpt_pts + "");
            Bouton7.setBackground(Color.BLUE);
            
        }
        else{
            cpt_pts -= 1;
            Label_Score.setText(cpt_pts + "");
        }
    }//GEN-LAST:event_Bouton7ActionPerformed

    private void Bouton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton8ActionPerformed
        // TODO add your handling code here:
      
        if (Bouton8.getBackground() == Color.CYAN) {
            Bouton8.setBackground(Color.BLUE);
            supp_bouton_blanc();
            allumerCaseAlea();
            cpt_pts += 1;
            Label_Score.setText(cpt_pts + "");
            cpt_coup += 1;
            if (cpt_coup == 1) {
              chrono.start();
              
            }
        }
        else if(Bouton8.getBackground() == Color.white) {
            cpt_pts -= 3;
            Label_Score.setText(cpt_pts + "");
            Bouton8.setBackground(Color.BLUE);
            
        }
        else{
            cpt_pts -= 1;
            Label_Score.setText(cpt_pts + "");
        }
    }//GEN-LAST:event_Bouton8ActionPerformed

    private void Bouton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton9ActionPerformed
        // TODO add your handling code here:
        if (Bouton9.getBackground() == Color.CYAN) {
            Bouton9.setBackground(Color.BLUE);
            supp_bouton_blanc();
            allumerCaseAlea();
            cpt_pts += 1;
            Label_Score.setText(cpt_pts + "");
            cpt_coup += 1;
            if (cpt_coup == 1) {
              chrono.start();
              
            }
        }
        else if(Bouton9.getBackground() == Color.white) {
            cpt_pts -= 3;
            Label_Score.setText(cpt_pts + "");
            Bouton9.setBackground(Color.BLUE);
            
        }
        else {
            cpt_pts -= 1;
            Label_Score.setText(cpt_pts + "");
        }
    }//GEN-LAST:event_Bouton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fenetreDeJeu().setVisible(true);
                
                               
            }
        });
    }
    
    public void allumerCaseAlea() {
        int nbbutt;
        int bouton_piege;
        int presence_piege;
        nbbutt = new Random().nextInt(9)+ 1 ;
        System.out.println(nbbutt);
        
        if (nbbutt == 1) {
            Bouton1.setBackground(Color.CYAN);
        }
        if (nbbutt == 2) {
            Bouton2.setBackground(Color.CYAN);
        }
        if (nbbutt == 3) {
            Bouton3.setBackground(Color.CYAN);
        }
        if (nbbutt == 4) {
            Bouton4.setBackground(Color.CYAN);
        }
        if (nbbutt == 5) {
            Bouton5.setBackground(Color.CYAN);
        }
        if (nbbutt == 6) {
            Bouton6.setBackground(Color.CYAN);
        }
        if (nbbutt == 7) {
            Bouton7.setBackground(Color.CYAN);
        }
        if (nbbutt == 8) {
            Bouton8.setBackground(Color.CYAN);
        }
        if (nbbutt == 9) {
            Bouton9.setBackground(Color.CYAN);
        }
        
        presence_piege = new Random().nextInt(5) + 1;
        
        if (presence_piege == 4) {
        
        bouton_piege = new Random().nextInt(9) + 1;
                
         if (bouton_piege == 1 && Bouton1.getBackground() != Color.CYAN) {
            Bouton1.setBackground(Color.white);
        }
        
         if (bouton_piege == 2 && Bouton1.getBackground() != Color.CYAN) {
            Bouton2.setBackground(Color.white);
        }
         
         if (bouton_piege == 3 && Bouton1.getBackground() != Color.CYAN) {
            Bouton3.setBackground(Color.white);
        }
          
         if (bouton_piege == 4 && Bouton1.getBackground() != Color.CYAN) {
            Bouton4.setBackground(Color.white);
        }
           
         if (bouton_piege == 5 && Bouton1.getBackground() != Color.CYAN) {
            Bouton5.setBackground(Color.white);
        }
            
         if (bouton_piege == 6 && Bouton1.getBackground() != Color.CYAN) {
            Bouton6.setBackground(Color.white);
        }
             
          if (bouton_piege == 7 && Bouton1.getBackground() != Color.CYAN) {
            Bouton7.setBackground(Color.white);
        }
          
          if (bouton_piege == 8 && Bouton1.getBackground() != Color.CYAN) {
            Bouton8.setBackground(Color.white);
        }
         
          if (bouton_piege == 9 && Bouton1.getBackground() != Color.CYAN) {
            Bouton9.setBackground(Color.white);
        }
        } 
    }
    
    
    public void supp_bouton_blanc() {
        if (Bouton1.getBackground() == Color.white) {
            Bouton1.setBackground(Color.blue);
        }
        
        if (Bouton2.getBackground() == Color.white) {
            Bouton2.setBackground(Color.blue);
        }
        
        if (Bouton3.getBackground() == Color.white) {
            Bouton3.setBackground(Color.blue);
        }
        
        if (Bouton4.getBackground() == Color.white) {
            Bouton4.setBackground(Color.blue);
        }
        
        if (Bouton5.getBackground() == Color.white) {
            Bouton5.setBackground(Color.blue);
        }
        
        if (Bouton6.getBackground() == Color.white) {
            Bouton6.setBackground(Color.blue);
        }
        
        if (Bouton7.getBackground() == Color.white) {
            Bouton7.setBackground(Color.blue);
        }
        
        if (Bouton8.getBackground() == Color.white) {
            Bouton8.setBackground(Color.blue);
        }
        
        if (Bouton9.getBackground() == Color.white) {
            Bouton9.setBackground(Color.blue);
        }
    }
    
    
    
    
    
    
    
    public void InitialiserPartie() {
        if (cpt_pts > record) {
            record = cpt_pts;
        }
        cpt_pts = 0;
        cpt_coup = 0;
        nb_parties += 1;
        nb_part.setText(nb_parties +"");
        score_max.setText(record + "");
        Label_Score.setText(cpt_pts + "");
        Bouton1.setBackground(Color.blue);
        Bouton2.setBackground(Color.blue);
        Bouton3.setBackground(Color.blue);
        Bouton4.setBackground(Color.blue);
        Bouton5.setBackground(Color.blue);
        Bouton6.setBackground(Color.blue);
        Bouton7.setBackground(Color.blue);
        Bouton8.setBackground(Color.blue);
        Bouton9.setBackground(Color.blue);
        
        allumerCaseAlea();
        
        //remettre le chrono au debut
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bouton1;
    private javax.swing.JButton Bouton2;
    private javax.swing.JButton Bouton3;
    private javax.swing.JButton Bouton4;
    private javax.swing.JButton Bouton5;
    private javax.swing.JButton Bouton6;
    private javax.swing.JButton Bouton7;
    private javax.swing.JButton Bouton8;
    private javax.swing.JButton Bouton9;
    private javax.swing.JLabel Label_Record;
    private javax.swing.JLabel Label_Score;
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jlab1;
    private javax.swing.JLabel nb_part;
    private javax.swing.JPanel panneau_chrono;
    private javax.swing.JPanel panneau_grille;
    private javax.swing.JPanel panneau_nom;
    private javax.swing.JPanel panneau_scores;
    private javax.swing.JLabel score_max;
    private javax.swing.JLabel tps_rest;
    // End of variables declaration//GEN-END:variables
}
